# Lista 08 - Comparando Regressões

# Exercício 01:

Analise o desempenho do kNN e de uma Regressão Linear Regularizada para **pelo menos um** dos conjuntos de dados disponível na [seção de regressão linear múltipla](http://college.cengage.com/mathematics/brase/understandable_statistics/7e/students/datasets/mlr/frames/frame.html) da página do *Livro Understandable Statistics* de Charles Brase e Corrinne Brase. Para o conjunto de dados que escolheu, execute a regressão linear múltipla para explicar o fator $X1$ dos dados ([ver descrição de um dos conjuntos](http://college.cengage.com/mathematics/brase/understandable_statistics/7e/students/datasets/mlr/frames/frame.html)) a partir dos outros fatores. 

Para a questão, faça as seguintes tarefas:

* Realize treino, validação e teste
* Compare as métricas no teste
* Diferente da lista anterior, reporte o erro quadrado médio no conjunto de teste.

In [74]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error
from sklearn.metrics import precision_recall_fscore_support
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [4]:
# Crimes
df = pd.read_excel("mlr06.xls")
df.head()

*** No CODEPAGE record, no encoding_override: will use 'ascii'


X1   X2  X3  X4  X5  X6  X7
0  478  184  40  74  11  31  20
1  494  213  32  72  11  43  18
2  643  347  57  70  18  16  16
3  341  565  31  71  11  25  19
4  773  327  67  72   9  29  24

In [45]:
X = df.values[:, 1:]
y = df.values[:, 0]
y_true = y
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [58]:
labels = list(set(y))

## K-Nearest Neighbors

In [90]:
knn = KNeighborsClassifier(n_neighbors=5).fit(X_test, y_test)

In [93]:
y_pred_knn = knn.predict(X_test)

In [91]:
y_test

array([ 357,  494,  437,  760,  863,  912,  940,  783,  619,  491,  652,
        776, 1504,  547,  799])

In [92]:
y_pred_knn

array([357, 357, 357, 619, 547, 491, 783, 491, 547, 491, 547, 357, 783,
       547, 547])

### Métricas

In [65]:
metrics_knn = precision_recall_fscore_support(y_test, y_pred_knn)
pd.DataFrame(metrics_knn[:-1], index=["Precisão", "Revocação", "F1"])

0    1         2    3         4    5    6    7    8    9    10  \
Precisão   0.25  0.0  0.200000  0.0  0.200000  0.0  0.0  0.0  0.0  0.0  0.0   
Revocação  1.00  0.0  1.000000  0.0  1.000000  0.0  0.0  0.0  0.0  0.0  0.0   
F1         0.40  0.0  0.333333  0.0  0.333333  0.0  0.0  0.0  0.0  0.0  0.0   

            11   12   13   14  
Precisão   0.0  0.0  0.0  0.0  
Revocação  0.0  0.0  0.0  0.0  
F1         0.0  0.0  0.0  0.0

### Erro médio quadrado

In [94]:
mean_squared_error(y_test, y_pred_knn)

126030.33333333333

## Regressão Linear Regularizada

In [68]:
lr = LinearRegression().fit(X_test, y_test)

In [69]:
y_pred_lr = lr.predict(X_test)

In [82]:
y_test

array([ 357,  494,  437,  760,  863,  912,  940,  783,  619,  491,  652,
        776, 1504,  547,  799])

In [81]:
y_pred_lr

array([ 323.86850976,  442.17697557,  439.16951833,  717.40925337,
        825.67546791, 1023.42605632,  942.96526559,  782.96649378,
        697.04832018,  823.95647397,  714.68548002,  516.67964004,
       1244.07392394,  683.42739372,  756.47122749])

### Erro médio quadrado

In [76]:
mean_squared_error(y_test, y_pred_lr)

19702.02988390343

Explique e discuta sobre os resultados encontrados no campo abaixo.

O erro médio quadrático do KNN ficou maior, para a escolha de 5 vizinhos, do que o erro médio quadrático da regressão linear. Isto foi inesperado, pois o KNN é usado para prever dados categóricos enquanto a regressão serve para dados numéricos.